name: build and upload

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check-out repository
      uses: actions/checkout@v4

    # - name: set up conda
    #   uses: s-weigand/setup-conda@v1
    #   with:
    #     update-conda: true
    #     python-version: ${{ matrix.python-version }}

    - name: set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        conda install -c conda-forge twine
        conda install -c conda-forge wheel
        conda install -c conda-forge setuptools
        conda install -c conda-forge pip
        conda install -c conda-forge gsl
        conda install -c conda-forge pycifrw
        conda install -c conda-forge six
        pip install "diffpy.structure==0.0.0" --index-url https://easyscience.github.io/pypi

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      if: runner.os == 'Linux'
      run: |
        conda install -c conda-forge numpy
        python setup.py install
        python conda-recipe/run_test.py

    - name: Upload Artifacts GitHub releases
      uses: ncipollo/release-action@v1
      with:
        draft: false
        prerelease: true
        allowUpdates: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ github.workspace }}/dist/*.whl
        tag: 0.0.2
        body: This is an alpha build of the pdffit2 library (0.0.2)

    - name: Checkout target repo
      uses: actions/checkout@v4
      env:
        REPO: easyScience/pypi
        REPO_PATH: pypi
      with:
        fetch-depth: 0
        token: ${{ secrets.ES_TOKEN }}
        repository: ${{ env.REPO }}
        path: ${{ env.REPO_PATH }}
        ref: "master"  # temporarily, switch branch from master
    # - name: Copy index to new repo
    #   env:
    #     SOURCE: index.html
    #     TARGET: pypi/diffpy-pdffit2/
    #   run: cp ${{ env.SOURCE }} ${{ env.TARGET }}
    # - name: Push
    #   shell: bash
    #   env:
    #     REPO_PATH: pypi
    #     GIT_USERNAME: action
    #     GIT_EMAIL: action@github.com
    #   run: |
    #     cd ${{ env.REPO_PATH }}
    #     git config --local user.name "${{ env.GIT_USERNAME }}"
    #     git config --local user.email "${{ env.GIT_EMAIL }}"
    #     git add .
    #     if [[ `git status --porcelain` ]]; then
    #       git commit -m "Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`"
    #       git push
    #     fi
